version: '3.1'

volumes:
  gems_store:
  database_store:
  redis_store:

services:
  rails:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    restart: always
    ports:
      - 3001:3000
    volumes:
      - gems_store:/usr/local/bundle/
      - .:/app/
    depends_on:
      - redis
      - database

  redis:
    image: redis
    restart: always
    ports:
      - 8081:6379
    volumes:
      - redis_store:/data/

  database:
    image: postgres
    restart: always
    ports:
      - 8080:5432
    volumes:
      - database_store:/var/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  